# Generated by Django 3.0.5 on 2020-06-02 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "add_municipalities"),
    ]

    operations = [
        migrations.DeleteModel(name="AppAction",),
    ]
