# Generated by Django 3.0.5 on 2020-06-02 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0002_auto_20200602_1209"),
    ]

    operations = [
        migrations.RemoveField(model_name="municipality", name="cities",),
        migrations.AddField(
            model_name="city",
            name="municipality",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="city",
                to="data_models.Municipality",
            ),
            preserve_default=False,
        ),
    ]
