# Generated by Django 3.0.7 on 2020-06-18 14:54

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.contrib.gis.geos import Point
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0003_auto_20200602_1311"),
    ]

    operations = [
        migrations.RemoveField(model_name="bbr", name="address",),
        migrations.RemoveField(model_name="bbr", name="bbr_categorical",),
        migrations.RemoveField(model_name="bbr", name="bbr_numeric",),
        migrations.RemoveField(model_name="bbr", name="kvhx",),
        migrations.RemoveField(model_name="bbr", name="zip_code",),
        migrations.RemoveField(model_name="house", name="bbr",),
        migrations.RemoveField(model_name="house", name="cities",),
        migrations.RemoveField(model_name="house", name="lat",),
        migrations.RemoveField(model_name="house", name="lon",),
        migrations.RemoveField(model_name="house", name="soil_type",),
        migrations.RemoveField(model_name="house", name="utm_x",),
        migrations.RemoveField(model_name="house", name="utm_y",),
        migrations.AddField(
            model_name="bbr",
            name="accsses_address",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buldings",
                to="data_models.House",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="building_area",
            field=models.IntegerField(default=0, verbose_name="Bygning areal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="carport_area",
            field=models.IntegerField(default=0, verbose_name="Carport areal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="commercial_area",
            field=models.IntegerField(default=0, verbose_name="Erhvervs areal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="garage_area",
            field=models.IntegerField(default=0, verbose_name="Garage areal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="ground_area",
            field=models.IntegerField(default=0, verbose_name="Grund areal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="num_baths",
            field=models.IntegerField(default=0, verbose_name="Antal badeværelser"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="num_floors",
            field=models.IntegerField(default=0, verbose_name="Antal etager"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="num_rooms",
            field=models.IntegerField(default=0, verbose_name="Antal værelser"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="num_toilets",
            field=models.IntegerField(default=0, verbose_name="Antal toiletter"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="other_area",
            field=models.IntegerField(default=0, verbose_name="Kælder/loftrum osv."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="outhouse_area",
            field=models.IntegerField(default=0, verbose_name="Udestue areal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bbr",
            name="roof_area",
            field=models.IntegerField(default=-1, verbose_name="Loft areal"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="access_id",
            field=models.CharField(
                default=1, max_length=40, verbose_name="Adgangs adresse id"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                default=Point(0, 0), srid=4326, verbose_name="Lokation"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="house",
            name="dawa_id",
            field=models.CharField(
                default=1, max_length=40, unique=True, verbose_name="DAWA_ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bbr",
            name="reconstruction_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Renoveringsår"
            ),
        ),
        migrations.AlterField(
            model_name="house",
            name="kvhx",
            field=models.CharField(
                default=1, max_length=200, unique=True, verbose_name="Kvhx"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="house",
            name="zip_code",
            field=models.IntegerField(default=1, verbose_name="Postnummer"),
            preserve_default=False,
        ),
    ]
