# Generated by Django 3.0.7 on 2020-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0004_auto_20200618_1654"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CategoricalBBR",
        ),
        migrations.DeleteModel(
            name="NumericBBR",
        ),
        migrations.AddField(
            model_name="bbr",
            name="heat_install",
            field=models.CharField(
                choices=[
                    ("1", "Fjernvarme/blokvarme"),
                    ("2", "Centralvarme fra eget anlæg, et-kammer fyr"),
                    ("3", "Ovne"),
                    ("5", "Varmepumpe"),
                    ("6", "\tCentralvarme med to fyringsenheder"),
                    ("7", "Elovne, elpaneler"),
                    ("8", "Gasradiator"),
                    ("9", "\tIngen varmeinstallation"),
                    ("99", "Blandet"),
                ],
                default="9",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="bbr",
            name="heat_supply",
            field=models.CharField(
                choices=[
                    ("0", "Ikke oplyst"),
                    ("1", "Varmepumpeanlæg"),
                    ("2", "Brændeovn o. lign."),
                    ("3", "Ovne til flydende brændsel"),
                    ("4", "Solpaneler"),
                    ("5", "Pejs"),
                    ("6", "Gasradiator"),
                    ("7", "Elovne, elpaneler"),
                    ("10", "Biogasanlæg"),
                    ("80", "Andet"),
                    ("90", "Ingen"),
                ],
                default="0",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="bbr",
            name="heat_type",
            field=models.CharField(
                choices=[
                    ("1", "Elektricitet"),
                    ("2", "Gasværksgas"),
                    ("3", "Flydende brændsel"),
                    ("4", "Fast brændsel"),
                    ("6", "Halm"),
                    ("7", "Naturgas"),
                    ("9", "Andet"),
                ],
                default="9",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="bbr",
            name="roofing_material",
            field=models.CharField(
                choices=[
                    ("1", "Built-up"),
                    ("2", "Tagpap"),
                    ("3", "Fibercement"),
                    ("4", "Cementsten"),
                    ("5", "Tegl"),
                    ("6", "Metalplader"),
                    ("7", "Stråtag"),
                    ("10", "Fibercement"),
                    ("11", "PVC"),
                    ("12", "Glas"),
                    ("20", "Grønne tage"),
                    ("80", "Ingen"),
                    ("90", "Andet materiale"),
                ],
                default="90",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="bbr",
            name="wall_material",
            field=models.CharField(
                choices=[
                    ("1", "Mursten"),
                    ("2", "Letbeton"),
                    ("3", "Plader af fibercement"),
                    ("4", "Bindingsværk"),
                    ("5", "Træbeklædning"),
                    ("6", "Betonelementer (etagehøje betonelementer)"),
                    ("8", "Metalplader"),
                    ("10", "Fibercement (asbestfri)"),
                    ("11", "PVC"),
                    ("12", "Glas"),
                    ("80", "Ingen"),
                    ("90", "Andet materiale"),
                ],
                default="90",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="bbr",
            name="water_supply",
            field=models.CharField(
                choices=[
                    ("1", "Alment vandforsyningsanlæg (tidligere offentligt)"),
                    ("2", "Privat, alment vandforsyningsanlæg"),
                    (
                        "3",
                        "\tEnkeltindvindingsanlæg (egen boring til 1 eller 2 ejendomme)",
                    ),
                    ("4", "Brønd"),
                    ("6", "Ikke alment vandforsyningsanlæg (forsyner < 10 ejendomme)"),
                    ("9", "\tIngen vandforsyning"),
                ],
                default="9",
                max_length=2,
            ),
        ),
    ]
