# Generated by Django 3.0.7 on 2020-07-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0011_auto_20200728_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbr',
            name='energy_type',
            field=models.CharField(choices=[('0', 'Ikke oplyst'), ('1', 'Gas fra værk'), ('2', '230 V el fra værk'), ('3', '400 V el fra værk'), ('4', 'Både 230 V el og gas fra værk'), ('5', 'Både 400 V el og gas fra værk'), ('6', 'Hverken el eller gas fra værk')], default='0', max_length=2, verbose_name='Primær Energiforsyning'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bbr',
            name='residential_type',
            field=models.CharField(choices=[('120', 'Enfamiliehuse'), ('110', 'Stuehuse til landbrug'), ('130', 'Række/kæde-huse'), ('132', 'Dobbelthus (to boliger med lodret adskillelse mellem enhederne)'), ('multi', 'Dobbelt-/flerfamiliehuse'), ('story', 'Etageboliger'), ('oth', 'Anden, herunder kollegier')], default='oth', max_length=7, verbose_name='Boligtype'),
            preserve_default=False,
        ),
    ]
