# Generated by Django 3.0.7 on 2020-07-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0012_auto_20200729_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbr',
            name='energy_type',
            field=models.CharField(choices=[('0', 'Ikke oplyst'), ('1', 'Gas fra værk'), ('2', '230 V el fra værk'), ('3', '400 V el fra værk'), ('4', 'Både 230 V el og gas fra værk'), ('5', 'Både 400 V el og gas fra værk'), ('6', 'Hverken el eller gas fra værk')], default='0', max_length=2, verbose_name='Primær Energiforsyning'),
        ),
        migrations.AlterField(
            model_name='bbr',
            name='heat_type',
            field=models.CharField(choices=[('0', 'Ikke oplyst'), ('1', 'Elektricitet'), ('2', 'Gasværksgas'), ('3', 'Flydende brændsel'), ('4', 'Fast brændsel'), ('6', 'Halm'), ('7', 'Naturgas'), ('9', 'Andet')], default='0', max_length=2, null=True, verbose_name='Primært Opvarmningsmiddel'),
        ),
    ]
