# Generated by Django 3.0.7 on 2020-07-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0013_auto_20200729_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbr',
            name='residential_type',
            field=models.CharField(choices=[('120', 'Enfamiliehuse'), ('110', 'Stuehuse til landbrug'), ('130', 'Række/kæde-huse'), ('140', 'Etagebolig-bygning, flerfamilehus eller to- familiehus (vandret adskillelse mellem enhederne)'), ('132', 'Dobbelthus (to boliger med lodret adskillelse mellem enhederne)'), ('multi', 'Dobbelt-/flerfamiliehuse'), ('story', 'Etageboliger'), ('oth', 'Anden, herunder kollegier')], max_length=7, verbose_name='Boligtype'),
        ),
    ]
