# Generated by Django 3.1.1 on 2020-12-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_models", "0017_auto_20200819_1543"),
    ]

    operations = [
        migrations.AddField(
            model_name="bbr",
            name="basement_area",
            field=models.IntegerField(default=0, verbose_name="Kælder størrelse"),
        ),
    ]
