from .graphs import (
    HISTOGRAM_GRAPH,
    MAP_GRAPH,
    MUNICIPALITY_GRAPH,
    SCATTER_GRAPH,
    TIME_GRAPH,
)

__all__ = [
    "MAP_GRAPH",
    "SCATTER_GRAPH",
    "HISTOGRAM_GRAPH",
    "MUNICIPALITY_GRAPH",
    "TIME_GRAPH",
]
