# Contains the mappings for categorical fields
HEAT_INSTALL_CHOICES = [
    ("0", "Ikke oplyst"),
    ("1", "Fjernvarme/blokvarme"),
    ("2", "Centralvarme fra eget anlæg, et-kammer fyr"),
    ("3", "Ovne"),
    ("5", "Varmepumpe"),
    ("6", "Centralvarme med to fyringsenheder"),
    ("7", "Elovne, elpaneler"),
    ("8", "Gasradiator"),
    ("9", "Ingen varmeinstallation"),
    ("99", "Blandet"),
]

HEAT_TYPE_CHOICES = [
    ("0", "Ikke oplyst"),
    ("1", "Elektricitet"),
    ("2", "Gasværksgas"),
    ("3", "Flydende brændsel"),
    ("4", "Fast brændsel"),
    ("6", "Halm"),
    ("7", "Naturgas"),
    ("9", "Andet"),
]

HEAT_SUPPLY_INSTALL_CHOICES = [
    ("0", "Ikke oplyst"),
    ("1", "Varmepumpeanlæg"),
    ("2", "Brændeovn o. lign."),
    ("3", "Ovne til flydende brændsel"),
    ("4", "Solpaneler"),
    ("5", "Pejs"),
    ("6", "Gasradiator"),
    ("7", "Elovne, elpaneler"),
    ("10", "Biogasanlæg"),
    ("80", "Andet"),
    ("90", "Ingen"),
]

WATER_SUPPLY_CHOICES = [
    ("0", "Ikke oplyst"),
    ("1", "Alment vandforsyningsanlæg (tidligere offentligt)"),
    ("2", "Privat, alment vandforsyningsanlæg"),
    ("3", "	Enkeltindvindingsanlæg (egen boring til 1 eller 2 ejendomme)"),
    ("4", "Brønd"),
    ("6", "Ikke alment vandforsyningsanlæg (forsyner < 10 ejendomme)"),
    ("9", "	Ingen vandforsyning"),
]

WALL_MATERIAL_CHOICES = [
    ("0", "Ikke oplyst"),
    ("1", "Mursten"),
    ("2", "Letbeton"),
    ("3", "Plader af fibercement"),
    ("4", "Bindingsværk"),
    ("5", "Træbeklædning"),
    ("6", "Betonelementer (etagehøje betonelementer)"),
    ("8", "Metalplader"),
    ("10", "Fibercement (asbestfri)"),
    ("11", "PVC"),
    ("12", "Glas"),
    ("80", "Ingen"),
    ("90", "Andet materiale"),
]

ENERGY_SUPPLY_CHOICES = [
    ("0", "Ikke oplyst"),
    ("1", "Gas fra værk"),
    ("2", "230 V el fra værk"),
    ("3", "400 V el fra værk"),
    ("4", "Både 230 V el og gas fra værk"),
    ("5", "Både 400 V el og gas fra værk"),
    ("6", "Hverken el eller gas fra værk"),
]

ROOFING_MATERIAL_CHOICES = [
    ("0", "Ikke oplyst"),
    ("1", "Built-up"),
    ("2", "Tagpap"),
    ("3", "Fibercement"),
    ("4", "Cementsten"),
    ("5", "Tegl"),
    ("6", "Metalplader"),
    ("7", "Stråtag"),
    ("10", "Fibercement"),
    ("11", "PVC"),
    ("12", "Glas"),
    ("20", "Grønne tage"),
    ("80", "Ingen"),
    ("90", "Andet materiale"),
]

PROPERTY_TYPE_CHOICES = [
    ("0", "Ikke oplyst"),
    ("1", "Egentlig beboelseslejlighed"),
    ("2", "Blandet erhverv og bolig med eget køkken."),
    ("3", "Enkeltværelse"),
    ("4", "Fællesbolig eller fælleshusholdning"),
    ("5", "Sommer-/fritidsbolig."),
    ("E", "Andet (bl.a. institutioner og erhverv)"),
]

KITCHEN_FACILITY = [
    ("0", "Ikke oplyst"),
    ("E", "Eget køkken"),
    ("F", "Adgang til fælles køkken"),
    ("G", "Fast kogeinstallation i værelse eller på gang"),
    ("H", "Ingen fast kogeinstallation"),
]

TOILET_FACILITY = [
    ("0", "Ikke oplyst"),
    ("T", "Vandskyllende toilet i bolig- eller erhvervsenheden"),
    ("A", "Vandskyllende toilet udenfor enheden"),
    (
        "B",
        "Anden type toilet udenfor enheden eller intet toilet i B forbindelse med enheden",
    ),
]

BATHING_FACILITY = [
    ("0", "Ikke oplyst"),
    ("V", "Badeværelser i enheden"),
    ("C", "Adgang til badeværelse"),
    ("D", "Hverken badeværelse eller adgang til badeværelse"),
]


RECIDENTIAL_TYPE_CHOICES = [
    ("110", "Stuehuse til landbrug"),
    ("120", "Enfamiliehuse"),
    ("130", "Række/kæde-huse"),
    ("131", "Række- og kædehus (lodret adskillelse mellem enhederne)"),
    ("132", "Dobbelthus (to boliger med lodret adskillelse mellem enhederne)"),
    (
        "140",
        "Etagebolig-bygning, flerfamilehus eller to- familiehus (vandret adskillelse mellem enhederne)",
    ),
    ("150" "Kollegium"),
    (
        "160",
        "Boligbygning til døgninstitution (plejehjem, alderdomshjem, børne- eller ungdomshjem)",
    ),
    ("185", "Anneks i tilknytning til helårsbolig."),
    ("190", "Anden bygning til helårsbeboelse"),
    (
        "210",
        "Bygning til erhvervsmæssig produktion vedrørende landbrug, gartneri, råstofudvinding o. lign",
    ),
    ("211", "Svinestald "),
    ("212", "Kvægstald "),
    ("213", "Fjerkræsstald "),
    ("214", "Minkhal"),
    ("215", "Væksthus"),
    ("216", "Foder-/ ladebygning (Bygning med ydervægge)"),
    ("217", "Maskinhus, løsdriftstald, garage o.a."),
    ("218", "Halmlade/staklade (Bygning uden ydervægge)"),
    ("219", "Anden bygning til landbrug, skovbrug, fiskeri eller råstofindvinding"),
    (
        "220",
        "Bygning til erhvervsmæssig produktion vedrørende industri, håndværk m.v. (fabrik, værksted o.lign.)",
    ),
    (
        "221",
        "Bygning til erhvervsmæssig industriproduktion herunder fødevareproduktion, hvor produktionsapparatet er en integreret del af bygningen",
    ),
    (
        "222",
        "Bygning til erhvervsmæssig industriproduktion herunder fødevareproduktion, hvor produktionsapparatet ikke er en integreret del af bygningen",
    ),
    ("223", "Værksted"),
    (
        "229",
        "Anden bygning til erhvervsmæssig produktion vedrørende industri, håndværk o. lign.",
    ),
    ("230", "El-, gas-, vand- eller varmeværk, forbrændingsanstalt m.v."),
    (
        "231",
        "Bygning til energiproduktion (herunder energiproduktion vedr. affaldsforbrænding o. lign. )",
    ),
    ("232", "Bygning til forsyning- og energidistribution "),
    ("233", "Bygning til vandforsyning"),
    ("234", "Bygninger til affaldshåndtering, rensningsanlæg o. lign"),
    ("239", "Anden bygning til forsyning- og energidistribution mv."),
    ("290", "Anden bygning til landbrug, industri etc."),
    (
        "310",
        "Transport- og garageanlæg (fragtmandshal, lufthavnsbygning, banegårdsbygning, parkeringshus). Garage med plads til et eller to køretøjer registreres med anvendelseskode 910",
    ),
    ("311", "Bygning til jernbane- og busdrift "),
    ("312", "Bygning til luftfart"),
    (
        "313",
        "Bygning til parkering- og transportanlæg i forbindelse med erhverv, med plads til mere end to køretøjer",
    ),
    (
        "314",
        "Bygning til parkering- og transportanlæg i tilknytning til boliger, med plads til mere end to køretøjer",
    ),
    ("315", "Havneanlæg"),
    ("319", "Andet transport anlæg"),
    ("320", "Bygning til kontor, handel, lager, herunder offentlig administration"),
    ("321", "Bygning til kontor"),
    ("322", "Bygning til handel og butik"),
    ("323", "Bygning til lager"),
    ("324", "Butikscenter og storcenter"),
    ("325", "Tankstation"),
    ("329", "Anden bygning til kontor, handel og lager"),
    (
        "330",
        "Bygning til hotel, restaurant, vaskeri, frisør og anden servicevirksomhed",
    ),
    ("331", "Hotel, kro eller konferencecenter med overnatningsmulighed"),
    ("332", "Bed & breakfast o.lign."),
    ("333", "Restaurant, café, kasino o. lign."),
    ("334", "Privat servicevirksomhed som frisør, vaskeri, netcafé o. lign."),
    ("339", "Anden byning til serviceerhverv"),
    ("390", "Anden bygning til transport, handel etc"),
    (
        "410",
        "Bygning til biograf, teater, erhvervsmæssig udstilling, bibliotek, museum, kirke o. lign.",
    ),
    ("411", "Biograf, teater o.lign."),
    ("412", "Museum"),
    ("413", "Bibliotek"),
    (
        "414",
        "Kirke eller anden bygning til trosudøvelse for statsanerkendte trossamfund",
    ),
    ("415", "Forsamlingshus"),
    ("416", "Konferencecenter uden overnatningsmuligheder"),
    ("419", "Anden bygning til kulturelle og religiøse formål"),
    (
        "420",
        "Bygning til undervisning og forskning (skole, gymnasium, forskningslaboratorium o.lign.)",
    ),
    ("421", "Grundskole (folkeskole, privatskole o. lign.)"),
    ("422", "Universitet"),
    ("429", "Anden bygning til undervisning"),
    ("430", "Bygning til hospital, sygehjem, fødeklinik o. lign."),
    ("431", "Hospital og sygehus"),
    ("432", "Hospice, behandlingshjem o.lign."),
    ("433", "Sundhedscenter, lægehus, fødeklinik o. lign."),
    ("439", "Anden bygning til sundhedsformål"),
    ("440", "Bygning til daginstitution"),
    ("441", "Daginstitution"),
    ("442", "Servicefunktion på døgninstitution"),
    ("443", "Kaserne"),
    ("444", "Fængsel, arresthus o. lign."),
    ("449", "Anden bygning til institutionsformål"),
    ("490", "Bygning til anden institution, herunder kaserne, fængsel o. lign."),
    ("510", "Sommerhus"),
    ("520", "Bygning til feriekoloni, vandrehjem o.lign. bortset fra sommerhus"),
    ("521", "Feriecenter, campingcenter o. lign."),
    ("522", "Ferielejlighed og fritidsbolig"),
    ("529", "Anden bygning til ferieformål"),
    (
        "530",
        "Bygning i forbindelse med idrætsudøvelse (klubhus, idrætshal, svømmehal o. lign.)",
    ),
    ("531", "Klubhus i forbindelse med fritids- og idrætsudøvelse"),
    ("532", "Svømmehal"),
    ("533", "Idrætshal"),
    ("534", "Tribune i forbindelse med stadion"),
    ("535", "Rideskole inklusiv ridehal, ridestald o. lign."),
    ("539", "Anden bygning til idrætsudøvelse o.lign."),
    ("540", "Kolonihavehus"),
    ("585", "Anneks i tilknytning til fritids- og sommerhus"),
    ("590", "Anden bygning til fritidsformål"),
    ("910", "Garage (med plads til et eller to køretøjer) "),
    ("920", "Carport"),
    ("930", "Udhus"),
    ("940", "Drivhus (ikke landbrug)"),
    ("950", "Fritliggende overdækket areal "),
    ("960", "Fritliggende udestue"),
    ("970", "Tiloversbleven landbrugsbygning"),
    ("multi", "Dobbelt-/flerfamiliehuse"),
    ("321", "Bygning til kontor"),
    ("412", "Museum"),
    ("322", "Bygning til handel og butik"),
    ("323", "Bygning til lager"),
    ("510", "Sommerhus"),
    ("540", "Kolonihavehus"),
    ("story", "Etageboliger"),
    ("oth", "Anden, herunder kollegier"),
]
