name: Runs deployment steps and analyses code
"on":
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Build and Push Docker image to Dockerhub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push visualizer to Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: "${{ secrets.docker_user }}"
          password: "${{ secrets.docker_token }}"
          repository: rotendahl/bolius
          tag_with_sha: true
          tag_with_ref: true

      - name: Push nginx to docker hub
        uses: docker/build-push-action@v1
        with:
          dockerfile: nginx/Dockerfile
          path: nginx
          username: "${{ secrets.docker_user }}"
          password: "${{ secrets.docker_token }}"
          repository: rotendahl/visualizer_nginx
          tag_with_sha: true
          tag_with_ref: true
  coverage:
    name: Upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup Enviroment
        run: cp .env.example .env
      - name: Builds the stack
        run: docker-compose build
      - name: Generating coverage
        run: docker-compose run visualizer coverage run --source='.' manage.py test
      - name: Converting coverage
        run: docker-compose run visualizer coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          token: "${{ secrets.code_cov_token }}"
          file: ./coverage.xml
