name: Build & Publish Docker image
on:
  push:
    branches:
      - master
jobs:
  push_to_registry:
    name: Build and Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.doceker_user }}
          password: ${{ secrets.docker_token }}
          repository: rotendahl/bolius
          tag_with_sha: true
          tag_with_ref: true
