name: Run tests & Analyse code

on:
  push:
    branches-ignore: "master"

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/auto-cancel-redundant-job@v1
      - name: Setup Enviroment
        run: cp .env.example .env
      - name: Builds the stack
        run: docker-compose build
      - name: Test
        run: docker-compose run data_manager ./manage.py test
      - uses: actions/upload-artifact@v2.1.3
        if: always()
        with:
          name: selenium-screens
          path: ./test-screens

      - name: Check formatting (Black)
        run: docker-compose run data_manager black --check .
      - name: Static error check (Flake8)
        run: docker-compose run data_manager flake8
      - name: Import checks (isort)
        run: docker-compose run data_manager isort --check --profile black .
      - name: Generating coverage
        run: docker-compose run data_manager coverage run --source='.' manage.py test
      - name: Converting coverage
        run: docker-compose run data_manager coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.12
        with:
          token: ${{ secrets.code_cov_token }}
          file: ./coverage.xml
      - name: Create and upload UML diagram
        run: mkdir -p UML && docker-compose run data_manager ./manage.py graph_models data_models -o UML/UML_diagram.png
      - uses: actions/upload-artifact@v2.1.3
        with:
          name: UML_diagram.png
          path: UML
